const fs = require("fs");
const path = require("path");

const output = path.join(__dirname, "..", "dist");
const pages = [
  ["weekday-finder", "Weekday Finder", "Find the weekday for any Gregorian date from 1583 onward."],
  ["age-calculator", "Age Calculator", "Calculate exact age in years, months and days."],
  ["date-difference", "Date Difference Calculator", "Measure the duration between any two dates."],
  ["working-days", "Working Days Calculator", "Count business days using weekend rules, Indian fixed-date presets and custom holidays."],
  ["date-add-subtract", "Add or Subtract Dates", "Move a date forward or backward by days, weeks, months or years."],
  ["weekday-in-month", "Find Specific Weekdays in a Month", "List every selected weekday in a chosen month."],
  ["countdown", "Countdown Calculator", "Count the days remaining until an important date."],
  ["week-number", "ISO Week Number Calculator", "Find the ISO week number and ISO week-year for a date."],
  ["leap-year", "Leap-Year Checker", "Check whether a year is a leap year under Gregorian calendar rules."],
  ["monthly-calendar", "Printable Monthly Calendar", "Generate and print a clean calendar for any month from 1583 onward."]
];

function header() {
  return `<header class="topbar"><a class="brand" href="index.html" aria-label="DayFinder home"><span class="brand-mark" aria-hidden="true">D</span><span>DayFinder</span><span class="brand-family">by Avyuha</span></a><div class="header-actions"><nav class="nav" aria-label="Primary navigation"><a href="index.html#tools" data-i18n="navTools">Tools</a><a href="guides.html" data-i18n="navGuides">Guides</a><a href="faq.html">FAQ</a><a href="about.html" data-i18n="navAbout">About</a></nav><label class="skip-link" for="language">Language</label><select id="language" class="language-select" aria-label="Language"><option value="en">English</option><option value="te">తెలుగు</option><option value="hi">हिन्दी</option></select></div></header>`;
}

function footer() {
  return `<footer><div class="container footer-shell"><div><a class="footer-brand" href="index.html">DayFinder by Avyuha</a><p>Private, practical date tools that work in your browser.</p></div><nav class="footer-links" aria-label="Footer navigation"><a href="index.html#tools">All tools</a><a href="guides.html">Guides</a><a href="faq.html">FAQs</a><a href="privacy.html">Privacy</a><a href="https://avyuha-website.web.app" rel="noopener">Avyuha ↗</a></nav></div><div class="container footer-meta"><span>© 2026 Avyuha</span><span>Gregorian calculations from 1583 onward</span></div></footer>`;
}

function shell(title, description, bodyClass, body) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | DayFinder by Avyuha</title><meta name="description" content="${description}"><meta name="theme-color" content="#0d493d"><link rel="canonical" href="https://dayfinder-avyuha.web.app/${bodyClass ? `${bodyClass}.html` : ""}"><link rel="icon" href="icon.svg" type="image/svg+xml"><link rel="manifest" href="manifest.webmanifest"><link rel="stylesheet" href="styles.css"></head>
<body${bodyClass ? ` data-tool="${bodyClass}"` : ""}>${header()}${body}${footer()}<script src="date-core.js"></script><script src="app.js"></script></body></html>`;
}

for (const [id, title, description] of pages) {
  fs.writeFileSync(path.join(output, `${id}.html`), shell(title, description, id, `<main class="container page-space"><div id="tool-root"></div></main>`));
}

const guideBody = `<main class="container page-space"><section class="page-title"><p class="eyebrow">LEARN WITH DAYFINDER</p><h1>Date calculation guides</h1><p>Short explanations of the rules behind the tools, with practical examples.</p></section><div class="article-grid"><article class="article-card"><h2>How weekdays are calculated</h2><p>DayFinder converts a valid date into a day count and maps the remainder after division by seven to Sunday through Saturday. The tool uses the proleptic Gregorian calendar consistently from 1583 onward.</p><p><strong>Example:</strong> 15 August 1947 was a Friday.</p></article><article class="article-card"><h2>The Gregorian leap-year rule</h2><p>A year is a leap year when it is divisible by 4, except century years must also be divisible by 400. Therefore 2000 was a leap year, while 1900 and 2100 are not.</p></article><article class="article-card"><h2>Counting working days</h2><p>Choose a date range and weekend pattern. The calculator examines each date, excludes weekends, then excludes selected fixed-date and custom holidays. Always enter the current official holiday list for payroll, banking, legal or contractual work.</p></article><article class="article-card"><h2>ISO week numbers</h2><p>ISO 8601 weeks start on Monday. Week 1 is the week containing the year’s first Thursday. This means some late-December dates belong to week 1 of the next ISO year, and some early-January dates belong to the previous ISO year.</p></article><article class="article-card"><h2>Exact age</h2><p>Exact age is reported as completed years, then completed months, then remaining days. It is more informative than simply dividing the total number of days by 365.</p></article><article class="article-card"><h2>Historical-date caution</h2><p>Different countries adopted the Gregorian calendar in different years. DayFinder applies Gregorian rules backward consistently from 1583. Researchers should verify the historical calendar used in the place and period they are studying.</p></article></div></main>`;
fs.writeFileSync(path.join(output, "guides.html"), shell("Date Calculation Guides", "Learn Gregorian date rules, working-day counting, ISO weeks and exact age calculations.", "guides", guideBody));

const faqBody = `<main class="container page-space"><section class="page-title"><p class="eyebrow">COMMON QUESTIONS</p><h1>DayFinder FAQs</h1><p>Clear answers about accuracy, privacy, holidays and offline use.</p></section><div class="faq-list"><details open><summary>Which calendar does DayFinder use?</summary><p>It uses the proleptic Gregorian calendar from 1583 onward. It does not convert dates from the Julian, Hindu, Islamic or other calendars.</p></details><details><summary>Are Indian holidays complete?</summary><p>No. The Working Days Calculator includes three national fixed-date references and a small selection of state fixed-date references. Festival, bank and gazette holidays change by year and location, so add the official dates manually.</p></details><details><summary>Can I use the results for legal or payroll decisions?</summary><p>Use DayFinder as a planning aid, then verify critical results against your organisation’s policy, contract and the relevant official calendar.</p></details><details><summary>Does DayFinder upload my dates?</summary><p>No. Calculations run in your browser and DayFinder does not require an account. Avoid entering personal information beyond the dates needed for a calculation.</p></details><details><summary>Does it work offline?</summary><p>After one successful online visit, supported browsers can cache the app for offline use. External Avyuha and GitHub links still require internet access.</p></details><details><summary>Why can historical results differ from old records?</summary><p>Regions adopted the Gregorian calendar at different times. Old documents may use a local or Julian calendar, while DayFinder applies Gregorian rules consistently.</p></details></div></main>`;
fs.writeFileSync(path.join(output, "faq.html"), shell("Frequently Asked Questions", "Answers about DayFinder accuracy, calendars, Indian holiday presets, privacy and offline use.", "faq", faqBody));

const aboutBody = `<main class="container page-space"><section class="page-title"><p class="eyebrow">AN AVYUHA PRODUCT</p><h1>Simple date tools, built for practical work.</h1><p>DayFinder by Avyuha brings everyday calendar calculations into one fast, private and accessible toolkit.</p></section><div class="article-grid"><article class="article-card"><h2>What it is</h2><p>A collection of ten browser-based utilities for weekdays, ages, date ranges, working days, schedules, ISO weeks, leap years and printable calendars.</p></article><article class="article-card"><h2>Who it helps</h2><p>Students, teachers, HR and payroll staff, project managers, researchers, event planners, logistics teams, legal administrators and families can use the tools for routine planning.</p></article><article class="article-card"><h2>How it works</h2><p>Calculations run locally with standard JavaScript date logic and DayFinder’s tested Gregorian date engine. No sign-in or server calculation is required.</p></article><article class="article-card"><h2>Important limitation</h2><p>DayFinder is an informational planning tool. Verify dates against official sources for legal, payroll, banking, historical or safety-critical decisions.</p></article></div></main>`;
fs.writeFileSync(path.join(output, "about.html"), shell("About DayFinder", "About DayFinder by Avyuha, a private browser-based toolkit for everyday calendar calculations.", "about", aboutBody));

const privacyBody = `<main class="container page-space"><section class="page-title"><p class="eyebrow">PRIVACY</p><h1>Your date calculations stay in your browser.</h1><p>Last updated: 12 September 2026</p></section><article class="prose"><h2>Calculations</h2><p>DayFinder performs calculator operations on your device. Dates entered into the tools are not intentionally transmitted to or stored by DayFinder.</p><h2>Local preferences</h2><p>Your language choice and offline files may be stored by your browser using local storage and service-worker caching. You can remove them through your browser settings.</p><h2>Hosting logs</h2><p>The hosting provider may process standard technical request information, such as IP address, browser type and requested page, for security and service operation.</p><h2>Analytics and advertising</h2><p>This version does not declare an analytics or advertising integration. If either is added later, this notice and any required consent controls should be updated before activation.</p><h2>External links</h2><p>Links to Avyuha or other websites are governed by those websites’ own privacy practices.</p><h2>Important note</h2><p>Do not rely on DayFinder as the sole source for legal, payroll, banking, medical or official decisions. Confirm critical dates with the appropriate authority.</p></article></main>`;
fs.writeFileSync(path.join(output, "privacy.html"), shell("Privacy", "DayFinder privacy information covering browser calculations, local preferences, caching and hosting logs.", "privacy", privacyBody));

console.log(`Generated ${pages.length + 4} pages.`);
